### ISSUE TITLE
Crash when tapping the Grass tile on the build screen

### ISSUE THREAD

**Issue by budidino** [Drauthius/a-village-in-the-sky#1]
v0.1.1 (I think)

Just downloaded the game to try it out but as soon as I tap to build my first Grass field I get this crash:

> Error
> 
> src/game/rendersystem.lua:316: attempt to compare number with nil
> 
> 
> Traceback
> 
> main.lua:178: in function 'handler'
> src/game/rendersystem.lua:316: in function '_drawEntity'
> src/game/rendersystem.lua:146: in function 'draw'
> lib/lovetoys/src/Engine.lua:252: in function 'draw'
> src/game/init.lua:382: in function 'func'
> lib/hump/camera.lua:141: in function 'draw'
> src/game/init.lua:381: in function 'oldDraw'
> lib/gfx/screen.lua:78: in function 'draw'
> main.lua:112: in function <main.lua:80>
> [C]: in function 'xpcall'

**Comment by Drauthius** [comment]
Does it happen every time? On which platform are you running the game?
